version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "14:00"
      timezone: "UTC"
    target-branch: "main"
    open-pull-requests-limit: 20
    commit-message:
      prefix: "chore(deps)"
    registries:
      - npm-github
