export enum AssetType {
  SAVING_ACCOUNT = 'SAVING_ACCOUNT',
  CHECKING_ACCOUNT = 'CHECKING_ACCOUNT',
  SHARE_SAVINGS_PLAN = 'SHARE_SAVINGS_PLAN',
  SHARE_ACCOUNT = 'SHARE_ACCOUNT',
  CRYPTO_CURRENCY = 'CRYPTO_CURRENCY',
}

export enum Company {
  CREDIT_AGRICOLE = 'CREDIT_AGRICOLE',
  BOURSORAMA = 'BOURSORAMA',
  REVOLUT = 'REVOLUT',
  TRADING_212 = 'TRADING_212',
  BOURSE_DIRECT = 'BOURSE_DIRECT',
  TRADE_REPUBLIC = 'TRADE_REPUBLIC',
  LEDGER = 'LEDGER',
  BINANCE = 'BINANCE',
  COINBASE = 'COINBASE',
  ABEILLE_ASSURANCE = 'ABEILLE_ASSURANCE',
  YOMONI = 'YOMONI',
}
