export enum AssetType {
  SAVING_ACCOUNT = 'SAVING_ACCOUNT',
  CHECKING_ACCOUNT = 'CHECKING_ACCOUNT',
  SHARE_SAVINGS_PLAN = 'SHARE_SAVINGS_PLAN',
  SHARE_ACCOUNT = 'SHARE_ACCOUNT',
  CRYPTO_CURRENCY = 'CRYPTO_CURRENCY',
}
