version: "3.3"
services:
  local-database:
    image: postgres:alpine
    shm_size: 8g
    ports:
      - 55432:5432
    command: postgres -c 'max_connections=120'
    environment:
      POSTGRES_DB: investment-tracker
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "admin-local"
    volumes:
      - investment-tracker-pgdump:/var/lib/postgresql/dump
      - investment-tracker-pgdata:/var/lib/postgresql/data
  integration-testing:
    image: postgres:alpine
    shm_size: 8g
    ports:
      - 56432:5432
    command: postgres -c 'max_connections=120'
    environment:
      POSTGRES_DB: investment-tracker
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "admin-integration"
    volumes:
      - investment-tracker-e2e-pgdump:/var/lib/postgresql/dump
      - investment-tracker-e2e-pgdata:/var/lib/postgresql/data

volumes:
  investment-tracker-pgdump:
  investment-tracker-pgdata:
  investment-tracker-e2e-pgdump:
  investment-tracker-e2e-pgdata:



    POSTGRES_DB: investment-tracker
    POSTGRES_USER: investment-admin
    POSTGRES_PASSWORD: 5H!&qSZC$*Ea
