export enum StockCategory {
  ENERGY = 'ENERGY',
  MATERIALS = 'MATERIALS',
  INDUSTRIALS = 'INDUSTRIALS',
  CONSUMER_DISCRETIONARY = 'CONSUMER_DISCRETIONARY',
  CONSUMER_STABLES = 'CONSUMER_STABLES',
  HEALTH_CARE = 'HEALTH_CARE',
  FINANCIALS = 'FINANCIALS',
  INFORMATION_TECHNOLOGY = 'INFORMATION_TECHNOLOGY',
  TELECOMMUNICATION_SERVICES = 'TELECOMMUNICATION_SERVICES',
  UTILITIES = 'UTILITIES',
  REAL_ESTATE = 'REAL_ESTATE',
}
